Features/nklns/kan 45
raynelz/SpaceProject pull request #2
Opened 2024-08-22 15:23 UTC by nklns

Feature: Добавлен MVC для экрана Launch.
UI: Экран сверстан, добавлены ячейки для демонстрации работы.
Темы: Светлая и темная темы работают корректно.

2024-08-22 16:42 UTC, raynelz requested changes

2024-08-22 16:42 UTC, raynelz commented on SpaceProject/Application/SceneDelegate.swift
Зачем пушишь SceneDelegate?? У вас rootView приложения это главный экран

2024-08-22 16:42 UTC, raynelz commented on SpaceProject/Modules/Main/Controller/LaunchViewController.swift
> +    private func setupNavigationBar() {
private методы вынеси в отдельный private extension

2024-08-22 16:42 UTC, raynelz commented on SpaceProject/Modules/Main/Controller/LaunchViewController.swift
> +        let leftButton = UIBarButtonItem(
пробел где?

2024-08-22 16:42 UTC, raynelz commented on SpaceProject/Modules/Main/Controller/LaunchViewController.swift
> +    @objc private func backButtonTapped() {
тут тоже пробел

2024-08-22 16:42 UTC, raynelz commented on SpaceProject/Modules/Main/Controller/LaunchViewController.swift
> +    private func setupTableView() {
тут тоже, говорите что надо правила линтера поменять

2024-08-22 16:42 UTC, raynelz commented on SpaceProject/Modules/Main/Controller/LaunchViewController.swift
> +    private func setupTableView() {
и функцию назовы setupBehavior как и договаривались

2024-08-22 16:42 UTC, raynelz commented on SpaceProject/Modules/Main/Controller/LaunchViewController.swift
> +            fatalError("Ячейка не найдена")
создавай здесь пустую ячейку чтобы приложение не падало. UITableViewCell

2024-08-22 16:42 UTC, raynelz commented on SpaceProject/Modules/Main/Controller/LaunchViewController.swift
> +extension LaunchViewController: UITableViewDataSource {
В будущем делай на diffableDataSource

2024-08-22 16:42 UTC, raynelz commented on SpaceProject/Modules/Main/Controller/LaunchViewController.swift
> +    func tableView(_ tableView: UITableView, viewForFooterInSection section: Int) -> UIView? {
это для чего?

2024-08-22 16:42 UTC, raynelz commented on SpaceProject/Modules/Main/Model/Launch.swift
> +func makeLaunches() -> [Launch] {
почему в модели у тебя лежит функция???

2024-08-22 16:42 UTC, raynelz commented on SpaceProject/Modules/Main/Model/Launch.swift
> +func makeLaunches() -> [Launch] {
это должно быть тогда отдельным Mock-файлом. Структура со статик константой

2024-08-22 16:42 UTC, raynelz commented on SpaceProject/Modules/Main/View/LaunchView.swift
> +    let tableView = UITableView(frame: .zero, style: .insetGrouped)
раз делаешь публичной таблицу, то будь добр закомментируй в таком формате `/// текст`

2024-08-22 16:42 UTC, raynelz commented on SpaceProject/Modules/Main/View/LaunchViewCell.swift
> +    func configure(with name: String, date: String, isSuccess: Bool) {
Почему не модель в аргументе???

2024-08-22 16:42 UTC, raynelz commented on SpaceProject/Modules/Main/View/LaunchViewCell.swift
> +    func setupCellAppearance() {
пробелыыыыы

2024-08-23 04:03 UTC, nklns commented on SpaceProject/Modules/Main/Controller/LaunchViewController.swift
> +    func tableView(_ tableView: UITableView, viewForFooterInSection section: Int) -> UIView? {
Сокращает расстояние между ячейками

2024-08-29 16:48 UTC, closed without merging